title: Icebear Service Status
buildFuture: true
defaultContentLanguage: en
languageCode: zh
baseURL: https://status.zeroicebear.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: 主站前端
      category: 管理组服务
      link: https://northlank.top
    - name: 主站后端
      category: 管理组服务
    - name: 审核站前端
      category: 管理组服务
      link: https://audit.northlank.top
    - category: 管理组服务
      name: 审核站后端
    - name: Bot服务
      category: 管理组服务
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo.jpg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: 北极熊网站
    - name: 管理组服务
      description: 内含地图查询主站,入群审核站,Bot 状态信息...
  description: 我们将持续监控我们的服务状态, 如有任何中断, 我们将在此发布说明.
  enableCustomHTML: true
  useLargeHeaderDesign: false
